[_]
schema-version = "0.2"
id = "hello-project"

[io.buildpacks]
builder = "heroku/builder:24"

[[io.buildpacks.group]]
id = "uv-buildpack"

    [io.buildpacks.group.script]
    api = "0.10"
    inline = """#!/bin/bash
set -eu

# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh
cp $HOME/.local/bin/uv .

# install dependencies
./uv sync

# put uv in a layer for caching
uv_layer="$1/uv"
mkdir -p $uv_layer/bin
cp uv $uv_layer/bin/uv

echo "[types]" > "${uv_layer}.toml"
echo "launch = true" >> "${uv_layer}.toml"
echo "cache = true" >> "${uv_layer}.toml"
echo "build = true" >> "${uv_layer}.toml"
"""
