name: Build with Pack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5

      - name: Build with Pack
        run: pack build python-inline-buildpack-app --path . --builder heroku/builder:24
